export const GET_POLL = 'API/POLL/GET';
export const FETCHING_POLL = 'API/POLL/FETCHING';
export const FETCHED_POLL = 'API/POLL/FETCHED';
export const ERROR_POLL = 'API/POLL/ERROR';

export const CAST_VOTE = 'API/CAST/VOTE';
export const CASTING_VOTE='API/CAST/CASTING';

export const CREATE_POLL = 'API/CAST/CREATE';
export const CREATING_POLL='API/CAST/CASTING_POLL';
